### ISSUE TITLE
How to search for perl-related items?

### ISSUE THREAD

**Issue by szabgab** [garu/Net-NVD#6]
I tried

```
my @cves = $nvd->search(
    keyword_search      => 'perl cpan',
);
```

I received 103 results. The first one was about "cPanel" not doing something "properly" and it was a "Cross-site scripting (XSS) vulnerability". Nothing to do with Perl or CPAN. I have not checked the others yet, but I wonder is there a better way to search that will only return Perl and/or CPAN related entries.

**Comment by garu** [comment]
Hi Gábor!

CVE data is unfortunately very poorly structured. Filtering with Net::NVD will give you an advantage, but you'll still need to do some manual work.

brian d foy has a very good repository doing just that, on https://github.com/briandfoy/cpan-security-advisory. He manually reviews perl/cpan related CVEs into their own security advisories, which are used by tools like [cpan-audit](https://metacpan.org/dist/CPAN-Audit/view/script/cpan-audit).

At the last Perl Toolchain Summit we started a CPAN Security Working Group, under MetaCPAN and the Perl Toolchain Gang, and created the https://github.com/metacpan/cpan-advisory-database repo, which will hold all reports for distributions stored under (Meta)CPAN in the portable format accepted by the [OSV](https://osv.dev/). The goal is to have an "official/sactioned" repository consumed by Github's Security Advisory initiative and integrated into their dependabot and OSV itself, like the security advisories for other package managers like npm, rubygems, pipy and cargo. We are also working on integrating those reports into the metacpan web interface, and who knows, maybe even cpanm/cpanm/cpm/cpanp/etc.

You are more than welcome to join, if this is something that interests you!
